### ISSUE TITLE
Некорректно указан тип данных аргумента `request_kwargs` в методе `http.client.Client.request`

### ISSUE THREAD

**Issue by DjaPy** [inplat/ipapp#20]
При попытке согласовать типы поймал такой кейс.
У клиента `http.client.Client` в методе `request` есть атрибут `request_kwargs` вы [определяете его тип](https://github.com/inplat/ipapp/blob/c13c9fc2c4fd88c082c6918fbc909fcd0f9b0506/ipapp/http/client.py#L102), как `Optional[Dict[str, Optional[str]]] = None,`
И раскрываете его в методе `aiohttp.client.ClientSession.request`, как (**request_kwargs). Но это не корректно, потому что в request есть разные аргументы, [например наш кейс](https://github.com/aio-libs/aiohttp/blob/b76be1e5bda8385f6d52eb02c9ebc7bcd0cc19dc/aiohttp/client.py#L323).

Предлагаю добавить аннотаци, как `Optional[Dict[str, Optional[Any]]] = None`,
Есть возможность это поправить или можно сделать PR?

**Comment by konstantin-stepanov** [comment]
да. это опечатка. поправлю

**Comment by konstantin-stepanov** [comment]
спасибо

**Comment by DjaPy** [comment]
Спасибо.
